/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.facitec.mec.view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import py.edu.facitec.mec.controller.ClienteController;
import py.edu.facitec.mec.controller.ClienteControllerImpl;
import py.edu.facitec.mec.mecanico.model.Cliente;

/**
 *
 * @author Javier Guilllen
 */
public class FormCliente extends javax.swing.JFrame {
    private ClienteController clienteController;
    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
        this.clienteController = new ClienteControllerImpl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        tfCredito = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre(s):");

        jLabel3.setText("Apellido(s):");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Credito:");

        tfCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        tfNombre.setCaretColor(new java.awt.Color(0, 51, 204));
        tfNombre.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        tfNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNombreMouseClicked(evt);
            }
        });
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNombreKeyPressed(evt);
            }
        });

        tfApellido.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        tfApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfApellidoMouseClicked(evt);
            }
        });

        tfDireccion.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        tfDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDireccionMouseClicked(evt);
            }
        });

        tfCredito.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        tfCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfCreditoMouseClicked(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(tfNombre)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDireccion)
                                    .addComponent(tfCredito))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnCerrar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        registrarCliente();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        habilitarConsultarGuardar(true);
        habilitarCampos(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            tfApellido.requestFocus();
        }
    }//GEN-LAST:event_tfNombreKeyPressed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        consultarClientePorCodigo(Integer.parseInt(tfCodigo.getText()));
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
       modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminar(Integer.parseInt(tfCodigo.getText()));
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tfNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombreMouseClicked
        // TODO add your handling code here:
        habilitarCampos(true);
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tfNombreMouseClicked

    private void tfApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfApellidoMouseClicked
        // TODO add your handling code here:
        habilitarCampos(true);
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tfApellidoMouseClicked

    private void tfDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDireccionMouseClicked
        // TODO add your handling code here:
        habilitarCampos(true);
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tfDireccionMouseClicked

    private void tfCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCreditoMouseClicked
        // TODO add your handling code here:
        habilitarCampos(true);
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tfCreditoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCredito;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    private void registrarCliente() {
        Cliente c = new Cliente();//se crea un objeto de tipo cliente y es una instacia de la clase
        //aqui se carga    
        c.setNombre(tfNombre.getText());//
        c.setApellido(tfApellido.getText());
        c.setDireccion(tfDireccion.getText());
        
        c.setCredito(Double.valueOf(tfCredito.getText())); // agarra el string y lo convierte a double de tipo nativo
        //c.setCredito(Double.parseDouble(tfCredito.getText()));
        
        clienteController.regitrarCliente(c); // luego de cargar los datos y se le pasa a controller, luego se deriva a la dao y luego 
        //pasa al base de datos
        JOptionPane.showMessageDialog(this, "Cliente registrado con exito", "Aviso", 1);
        limpiarCampos();
        
    }
    private void limpiarCampos(){
        tfCodigo.setText("");
        tfNombre.setText("");
        tfApellido.setText("");
        tfDireccion.setText("");
        tfCredito.setText("");
    }

    private void consultarClientePorCodigo(int codigo) {
       
       if(codigo != 0){
           Cliente cliente = clienteController.buscarClientePorCodigo(codigo);
           
           if(cliente != null){
               tfNombre.setText(cliente.getNombre());
               tfApellido.setText(cliente.getApellido());
               tfDireccion.setText(cliente.getDireccion());
               tfCredito.setText(String.valueOf(cliente.getCredito()));
              
               habilitarConsultarGuardar(false);
               habilitarCampos(false);
           } else{
           JOptionPane.showMessageDialog(this, "No existe cliente con este codigo!","Aviso",1);
           }
       }else{
          JOptionPane.showMessageDialog(this, "Debes digitar un numero!","Aviso",2); 
       }  
       
    }

    private void modificar() {
        Cliente c = new Cliente(Integer.parseInt(tfCodigo.getText()), tfNombre.getText(), tfApellido.getText(), tfDireccion.getText(), Double.parseDouble(tfCredito.getText()));
        
        clienteController.modificarCliente(c);
        //boolean result = clienteController.modificarCliente(c);
        JOptionPane.showMessageDialog(this, "Cliente actualizado con exito", "Aviso", 1);
        limpiarCampos();
        habilitarConsultarGuardar(true);
        /*if(result){
        
        }*/
    }

    private void eliminar(int codigo) {
        int opcion= JOptionPane.showConfirmDialog(this, "Estas seguro que quieres eliminar..?","Aviso", JOptionPane.YES_NO_OPTION);
        if (opcion==JOptionPane.YES_OPTION){
            clienteController.eliminarCliente(Integer.parseInt(tfCodigo.getText()));
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Cliente se ha borrado con exito", "Aviso", 1);
            habilitarCampos(true);
            habilitarConsultarGuardar(true);
        }
       
    }
    
    private void habilitarCampos(boolean valor){
       
        tfNombre.setEnabled(valor);
        tfApellido.setEnabled(valor);
        tfDireccion.setEnabled(valor);
        tfCredito.setEnabled(valor);
    }

   private void habilitarConsultarGuardar(boolean var){
       btnConsultar.setEnabled(var);
       btnGuardar.setEnabled(var);
       btnModificar.setEnabled(var);
       tfCodigo.setEnabled(var);
    }
   
  
   
    
}
